### ISSUE TITLE
Sketch Measure spec export not working

### ISSUE THREAD

**Issue by Liz-Newman** [utom/sketch-measure#531]
Hi, I am on using Sketch Version 51.3 and Sketch Measure Version 2.7.7, but my spec export is no longer working. 

Please let me know what to do to fix it.

**Comment by Liz-Newman** [comment]
<img width="301" alt="screen shot 2019-01-16 at 4 32 40 pm" src="https://user-images.githubusercontent.com/37350574/51283002-5bfeb800-19ac-11e9-8de8-375b88fc3135.png">


It just gets stuck like this

**Comment by Liz-Newman** [comment]
I am also on mac OS Sierra 10.12.6

**Comment by Pixelpusher93** [comment]
Same here. My whole team is affected.

**Comment by ellunium** [comment]
@Liz-Newman  you can give it a try to the latest version I have pushed on the Fork, see below:

# 2.7.8 Fork (2.7.7 SMFramework + 2.7.6 Fixes)
This is a fork I've created some time ago to fix Measure for Sketch v52+.

It includes a lot of changes, fixes and additions, the latest being the addition of the SMFramework from the v2.7.7 released by @utom recently, allowing for the `Toolbar 2.0` to work to certain extent.

Remember to **uninstall current plugin version**, **restart sketch** then, install the new version. 

[Download the latest zip file from the fork](https://github.com/ellunium/sketch-measure/archive/master.zip)

#### Check the version of the installed plugin:

Inside Sketch, Go to the menu:
- Plugins > Manage Plugins...
- Scroll down to "Sketch Measure"
    - It should say 2.7.8

# Changelog:

### **FIXED**
- fixed a bug with hex colors and multiline text line heights
- fixed bug to show radius when rectangle fill is an image when exporting
- fixed bug where styles would not show when exporting
- fixed radius support when exporting and marking
- fixed crash when marking overlays
- baseline fixes for Sketch v52+

### **CHANGED**
- updated SMFramework to latest version by @utom
- changed version to 2.7.8 for all languages
- changed radius validation to array, making it less prone to errors

### **ADDED**
- added a check in case CSSAtributes() gets fixed and they add back radius-border property
- added fix to show **Library and Local styles**, also added a check for sharedStyleID
- added **backward compatibility for notes** marked with older versions of the plugin
- added support to **show radius** even on masked items
- expanded **radius support to handle multiple radius** values on mark and export
- added support for oval, path, triangle, star and polygon shapes

# A note on Toolbar 2.0 (_beta_)

Some functions won't work as proper with the `Toolbar 2.0` (e.g.: `Text Styles` will not output).
Although I've added the SMFramework from the latest v2.7.7 released by @utom, it uses a compiled codebase done in XCode that I don't have access to make changes.

# Still not working?
Follow the steps below:

- [ ] Uninstall the plugin
- [ ] Quit Sketch
- [ ] Follow the steps bellow to remove the `PluginsWarehouse` folder
- [ ] [Download the latest zip file from the fork](https://github.com/ellunium/sketch-measure/archive/master.zip)
- [ ] Reinstall the plugin
- [ ] Test the `Mark Properties / Spec Export` again

> Remove the `PluginsWarehouse` folder that lives in `~/Library/Application Support/com.bohemiancoding.sketch3/`. This is where we cache plugin downloads, and if you’ve been testing different versions of your appcast, you probably have some old stuff there that’s worth cleaning.
> - Go to the Finder of Mac OS
> - From the “Go” menu navigate down to “Go to Folder” or...
> - Hit Command+Shift+G from the Mac OS X desktop or a Finder window
> - Paste the folder location `~/Library/Application Support/com.bohemiancoding.sketch3/`
> - Remove/Delete the `PluginsWarehouse` folder

I hope it helps  :) 

Justa a note:
I have stopped pushing more changes or fixes because I don’t want my fork to deviate too much from @utom’s masterpiece and original plugin, I don’t want my fork to become the main reference for this plugin. I see it only as a temporary fix for me, the community and people I work with, until @utom gets back to pushing more improvements to the original one when and if he has time to do so.

**Comment by cassandraallen** [comment]
I followed all of your un-install and re-install instructions to the T. I'm working with Sketch version 54.1. I tried downloading your latest zip file to install the 2.7.8 version of Measure but when I install it I'm still seeing the 2.7.7 version showing up in my plugin manager. Please advise or send the latest file asap.

**Comment by snuber** [comment]
> I followed all of your un-install and re-install instructions to the T. I'm working with Sketch version 54.1. I tried downloading your latest zip file to install the 2.7.8 version of Measure but when I install it I'm still seeing the 2.7.7 version showing up in my plugin manager. Please advise or send the latest file asap.

Same with me :-(

**Comment by thebrandongeiger** [comment]
Same here.

Sketch 55.1 (78136)
Sketch Measure 2.7.7

Could not get 2.7.8 installed after trying multiple times with instructions above. Export hang seems to be related to SVG icons or vector icon in my file. If I delete them all it exports correctly.

**Comment by arefbhrn** [comment]
Same...
Sketch 55.2 
Sketch Measure 2.7.7

**Comment by Jeason0228** [comment]
hey guy.you should try this one.sketch measure 2.8.0
i use sketch v55.1 and sketch 2.8.0 by ellunium
 #507

**Comment by Hirokoconut** [comment]
Using Sketch56.3 and  Measure2.8.1 
I've tried everything that has been posted on this page, but when my artboard has Notes (from Sketch Measure Tool) and/or complex symbols, it gets stuck and fails to export. :( My engineering teams need Notes to get my comments on design components, could you please fix it?

**Comment by snuber** [comment]
Hi Hirikoconut.
I installed Version 2.8.0 which fixed my problem.
https://github.com/ellunium/sketch-measure-latest

**Comment by carlosperez-glitch** [comment]
Hi,
I just uninstalled an old version of Sketch Measure, restarted my computer, then installed 2.8.1 on Sketch 69.2 and it still doesn´t work.

Any tips what i can do?

Thanks!!

**Comment by suqingogo1111** [comment]
sketch 70 and sketch measure 2.8.1 still doesn't work. Try all the steps above. And other tips can help?

**Comment by Blinkyb9** [comment]
I'm using Sketch 71.2 on Mac 11.3. I still get the stuck image with 2.8.1 Sketch Measure. Very frustrating.
